services:
  jenkins:
     build: ./builds/jenkins
     container_name: my_jenkins
     image: ${JENKINS_IMAGE_NAME}
     environment:
       HOST_JENKINS_HOME: ${PROJECT_PATH}/mount
     ports:
       - ${JENKINS_PORT}:8080
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./mount/jenkins_home:/var/jenkins_home
       - /usr/bin/docker:/usr/bin/docker

